-- Greatest Rap Albums bracket seed
--
-- This seed is NOT run automatically. It inserts a reusable template row that
-- organizers can reference when creating a "Greatest Rap Albums" bracket league.
-- Run manually against your target environment:
--
--   psql "$DATABASE_URL" -f supabase/seeds/rap_albums.sql
--
-- Or via Supabase CLI:
--   supabase db reset   (will pick this up if placed in supabase/seed.sql)
--   supabase db execute --file supabase/seeds/rap_albums.sql
--
-- The team_registry uses 100 albums. Bracket topology is 128-slot
-- (next power-of-2 above 100), giving 7 rounds. Organizers should
-- select the 64 or 128 entrants they want to include and trim the list.

insert into templates (name, type, team_registry, scoring_defaults, topology)
values (
  'Greatest Rap Albums',
  'bracket',
  '[
    {"id":"ra-001","name":"Illmatic","artist":"Nas","year":1994,"rank":1},
    {"id":"ra-002","name":"Ready to Die","artist":"The Notorious B.I.G.","year":1994,"rank":2},
    {"id":"ra-003","name":"Enter the Wu-Tang (36 Chambers)","artist":"Wu-Tang Clan","year":1993,"rank":3},
    {"id":"ra-004","name":"The Chronic","artist":"Dr. Dre","year":1992,"rank":4},
    {"id":"ra-005","name":"Reasonable Doubt","artist":"Jay-Z","year":1996,"rank":5},
    {"id":"ra-006","name":"Aquemini","artist":"OutKast","year":1998,"rank":6},
    {"id":"ra-007","name":"All Eyez on Me","artist":"2Pac","year":1996,"rank":7},
    {"id":"ra-008","name":"Tha Carter II","artist":"Lil Wayne","year":2005,"rank":8},
    {"id":"ra-009","name":"The Blueprint","artist":"Jay-Z","year":2001,"rank":9},
    {"id":"ra-010","name":"Good Kid, m.A.A.d City","artist":"Kendrick Lamar","year":2012,"rank":10},
    {"id":"ra-011","name":"To Pimp a Butterfly","artist":"Kendrick Lamar","year":2015,"rank":11},
    {"id":"ra-012","name":"Midnight Marauders","artist":"A Tribe Called Quest","year":1993,"rank":12},
    {"id":"ra-013","name":"Doggystyle","artist":"Snoop Dogg","year":1993,"rank":13},
    {"id":"ra-014","name":"Paid in Full","artist":"Eric B. & Rakim","year":1987,"rank":14},
    {"id":"ra-015","name":"The Score","artist":"Fugees","year":1996,"rank":15},
    {"id":"ra-016","name":"Southernplayalisticadillacmuzik","artist":"OutKast","year":1994,"rank":16},
    {"id":"ra-017","name":"Tha Carter III","artist":"Lil Wayne","year":2008,"rank":17},
    {"id":"ra-018","name":"The College Dropout","artist":"Kanye West","year":2004,"rank":18},
    {"id":"ra-019","name":"Only Built 4 Cuban Linx...","artist":"Raekwon","year":1995,"rank":19},
    {"id":"ra-020","name":"Stillmatic","artist":"Nas","year":2001,"rank":20},
    {"id":"ra-021","name":"Late Registration","artist":"Kanye West","year":2005,"rank":21},
    {"id":"ra-022","name":"The Low End Theory","artist":"A Tribe Called Quest","year":1991,"rank":22},
    {"id":"ra-023","name":"Me Against the World","artist":"2Pac","year":1995,"rank":23},
    {"id":"ra-024","name":"The Marshall Mathers LP","artist":"Eminem","year":2000,"rank":24},
    {"id":"ra-025","name":"3001: A Laced Odyssey","artist":"Flatbush Zombies","year":2016,"rank":25},
    {"id":"ra-026","name":"Supreme Clientele","artist":"Ghostface Killah","year":2000,"rank":26},
    {"id":"ra-027","name":"Madvillainy","artist":"Madvillain","year":2004,"rank":27},
    {"id":"ra-028","name":"The Don Killuminati","artist":"2Pac","year":1996,"rank":28},
    {"id":"ra-029","name":"36 Chambers","artist":"Wu-Tang Clan","year":1993,"rank":29},
    {"id":"ra-030","name":"My Beautiful Dark Twisted Fantasy","artist":"Kanye West","year":2010,"rank":30},
    {"id":"ra-031","name":"ATLiens","artist":"OutKast","year":1996,"rank":31},
    {"id":"ra-032","name":"Liquid Swords","artist":"GZA","year":1995,"rank":32},
    {"id":"ra-033","name":"Resurrection","artist":"Common","year":1994,"rank":33},
    {"id":"ra-034","name":"Speakerboxxx/The Love Below","artist":"OutKast","year":2003,"rank":34},
    {"id":"ra-035","name":"Moment of Truth","artist":"Gang Starr","year":1998,"rank":35},
    {"id":"ra-036","name":"Tical","artist":"Method Man","year":1994,"rank":36},
    {"id":"ra-037","name":"Criminal Minded","artist":"Boogie Down Productions","year":1987,"rank":37},
    {"id":"ra-038","name":"Raising Hell","artist":"Run-DMC","year":1986,"rank":38},
    {"id":"ra-039","name":"OB4CL2","artist":"Raekwon","year":2009,"rank":39},
    {"id":"ra-040","name":"The Blueprint 2","artist":"Jay-Z","year":2002,"rank":40},
    {"id":"ra-041","name":"Stankonia","artist":"OutKast","year":2000,"rank":41},
    {"id":"ra-042","name":"food & liquor","artist":"Lupe Fiasco","year":2006,"rank":42},
    {"id":"ra-043","name":"Black on Both Sides","artist":"Mos Def","year":1999,"rank":43},
    {"id":"ra-044","name":"Amerikkkas Most Wanted","artist":"Ice Cube","year":1990,"rank":44},
    {"id":"ra-045","name":"The Infamous","artist":"Mobb Deep","year":1995,"rank":45},
    {"id":"ra-046","name":"Hell on Earth","artist":"Mobb Deep","year":1996,"rank":46},
    {"id":"ra-047","name":"Straight Outta Compton","artist":"N.W.A","year":1988,"rank":47},
    {"id":"ra-048","name":"Ready to Die","artist":"Biggie","year":1994,"rank":48},
    {"id":"ra-049","name":"Section.80","artist":"Kendrick Lamar","year":2011,"rank":49},
    {"id":"ra-050","name":"DAMN.","artist":"Kendrick Lamar","year":2017,"rank":50},
    {"id":"ra-051","name":"Mr. Hood","artist":"EPMD","year":1991,"rank":51},
    {"id":"ra-052","name":"Ridin Dirty","artist":"UGK","year":1996,"rank":52},
    {"id":"ra-053","name":"Nas Is Like","artist":"Nas","year":1999,"rank":53},
    {"id":"ra-054","name":"The Documentary","artist":"The Game","year":2005,"rank":54},
    {"id":"ra-055","name":"Life After Death","artist":"The Notorious B.I.G.","year":1997,"rank":55},
    {"id":"ra-056","name":"Watch the Throne","artist":"Jay-Z & Kanye West","year":2011,"rank":56},
    {"id":"ra-057","name":"Trap Muzik","artist":"T.I.","year":2003,"rank":57},
    {"id":"ra-058","name":"word...Life","artist":"Brand Nubian","year":1994,"rank":58},
    {"id":"ra-059","name":"GZA Liquid Swords","artist":"GZA","year":1995,"rank":59},
    {"id":"ra-060","name":"Rolling Papers","artist":"Wiz Khalifa","year":2011,"rank":60},
    {"id":"ra-061","name":"Paul''s Boutique","artist":"Beastie Boys","year":1989,"rank":61},
    {"id":"ra-062","name":"Things Fall Apart","artist":"The Roots","year":1999,"rank":62},
    {"id":"ra-063","name":"The Miseducation of Lauryn Hill","artist":"Lauryn Hill","year":1998,"rank":63},
    {"id":"ra-064","name":"Enter the Dragon","artist":"RZA","year":2000,"rank":64},
    {"id":"ra-065","name":"God Son","artist":"Nas","year":2002,"rank":65},
    {"id":"ra-066","name":"Tical 2000","artist":"Method Man","year":1998,"rank":66},
    {"id":"ra-067","name":"Long.Live.A$AP","artist":"A$AP Rocky","year":2013,"rank":67},
    {"id":"ra-068","name":"Mr. Fantastik","artist":"MF DOOM","year":2009,"rank":68},
    {"id":"ra-069","name":"ATLiens Deluxe","artist":"OutKast","year":1996,"rank":69},
    {"id":"ra-070","name":"8701","artist":"Usher","year":2001,"rank":70},
    {"id":"ra-071","name":"De La Soul Is Dead","artist":"De La Soul","year":1991,"rank":71},
    {"id":"ra-072","name":"All Hail the Queen","artist":"Queen Latifah","year":1989,"rank":72},
    {"id":"ra-073","name":"Long Road to Hell","artist":"Scarface","year":1993,"rank":73},
    {"id":"ra-074","name":"Moment of Truth","artist":"Gang Starr","year":1998,"rank":74},
    {"id":"ra-075","name":"Based on a True Story","artist":"Cormega","year":2001,"rank":75},
    {"id":"ra-076","name":"Channel Orange","artist":"Frank Ocean","year":2012,"rank":76},
    {"id":"ra-077","name":"Infamous Mobb Deep","artist":"Mobb Deep","year":1999,"rank":77},
    {"id":"ra-078","name":"KOD","artist":"J. Cole","year":2018,"rank":78},
    {"id":"ra-079","name":"2014 Forest Hills Drive","artist":"J. Cole","year":2014,"rank":79},
    {"id":"ra-080","name":"Rodeo","artist":"Travis Scott","year":2015,"rank":80},
    {"id":"ra-081","name":"Astroworld","artist":"Travis Scott","year":2018,"rank":81},
    {"id":"ra-082","name":"Drip or Drown 2","artist":"Gunna","year":2019,"rank":82},
    {"id":"ra-083","name":"Stranger Things","artist":"A Boogie","year":2017,"rank":83},
    {"id":"ra-084","name":"Culture","artist":"Migos","year":2017,"rank":84},
    {"id":"ra-085","name":"4:44","artist":"Jay-Z","year":2017,"rank":85},
    {"id":"ra-086","name":"Invasion of Privacy","artist":"Cardi B","year":2018,"rank":86},
    {"id":"ra-087","name":"Igor","artist":"Tyler the Creator","year":2019,"rank":87},
    {"id":"ra-088","name":"Flower Boy","artist":"Tyler the Creator","year":2017,"rank":88},
    {"id":"ra-089","name":"Man on the Moon II","artist":"Kid Cudi","year":2010,"rank":89},
    {"id":"ra-090","name":"Man on the Moon","artist":"Kid Cudi","year":2009,"rank":90},
    {"id":"ra-091","name":"Acid Rap","artist":"Chance the Rapper","year":2013,"rank":91},
    {"id":"ra-092","name":"Coloring Book","artist":"Chance the Rapper","year":2016,"rank":92},
    {"id":"ra-093","name":"Run the Jewels 2","artist":"Run the Jewels","year":2014,"rank":93},
    {"id":"ra-094","name":"Mr. Morale & the Big Steppers","artist":"Kendrick Lamar","year":2022,"rank":94},
    {"id":"ra-095","name":"GNX","artist":"Kendrick Lamar","year":2024,"rank":95},
    {"id":"ra-096","name":"Dont Smile at Me","artist":"Billie Eilish","year":2017,"rank":96},
    {"id":"ra-097","name":"Detroit 2","artist":"Big Sean","year":2020,"rank":97},
    {"id":"ra-098","name":"Certified Lover Boy","artist":"Drake","year":2021,"rank":98},
    {"id":"ra-099","name":"Take Care","artist":"Drake","year":2011,"rank":99},
    {"id":"ra-100","name":"Nothing Was the Same","artist":"Drake","year":2013,"rank":100}
  ]'::jsonb,
  '{"round_points":{"1":1,"2":1,"3":2,"4":2},"champion_bonus":0,"has_third_place":false,"tiebreakers":["fewest_wrong"]}'::jsonb,
  '{"rounds":7,"slots_per_round":[64,32,16,8,4,2,1],"has_third_place":false}'::jsonb
);
